"""task card snapshot

Revision ID: 42c8178de7f0
Revises: a032d2fc7b14
Create Date: 2026-06-17 16:19:09.356401
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '42c8178de7f0'
down_revision: Union[str, None] = 'a032d2fc7b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_state', sa.Column('card_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_state', 'card_snapshot')
    # ### end Alembic commands ###
