"""go authorized unique per session

Revision ID: 5c6cf3a509d1
Revises: d3486213a2e2
Create Date: 2026-06-16 16:14:35.766329
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5c6cf3a509d1'
down_revision: Union[str, None] = 'd3486213a2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_go_authorized_per_session', 'go_authorization_event', ['session_id'], unique=True, postgresql_where=sa.text('authorized = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_go_authorized_per_session', table_name='go_authorization_event', postgresql_where=sa.text('authorized = true'))
    # ### end Alembic commands ###
