"""init briefing schema

Revision ID: d3486213a2e2
Revises: 
Create Date: 2026-06-16 10:36:07.360466
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd3486213a2e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_event_type', 'audit_event', ['event_type'], unique=False)
    op.create_index('ix_audit_task_created', 'audit_event', ['task_id', 'created_at'], unique=False)
    op.create_table('task_state',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('target_branch', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('red_team_required', sa.Boolean(), nullable=True),
    sa.Column('reviewer_user_id', sa.String(), nullable=True),
    sa.Column('mr_iid', sa.String(), nullable=True),
    sa.Column('source_branch', sa.String(), nullable=True),
    sa.Column('author_user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('briefing_session',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('target_branch', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('rounds_count', sa.Integer(), nullable=False),
    sa.Column('active_round_id', sa.String(), nullable=True),
    sa.Column('allowed_go_users', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_fields_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('author_user_id', sa.String(), nullable=False),
    sa.Column('bitrix_comment_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('ANSWERS_RECEIVED', 'APPROVED', 'BLOCKED_MANUAL', 'CANCELLED', 'COMPLETENESS_CHECK', 'ERROR', 'EXPIRED_WAITING_ANSWERS', 'GO_AUTH_CHECK', 'NEEDS_MORE_INFO', 'NEW', 'PLAN_GATE', 'QUESTIONS_GENERATED', 'READY_FOR_GO', 'WAITING_ANSWERS')", name='ck_session_state'),
    sa.ForeignKeyConstraint(['task_id'], ['task_state.task_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('uq_session_active_task', 'briefing_session', ['task_id'], unique=True, postgresql_where=sa.text("state NOT IN ('APPROVED', 'BLOCKED_MANUAL', 'CANCELLED', 'ERROR', 'PLAN_GATE')"))
    op.create_table('briefing_round',
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('target_branch', sa.String(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('author_user_id', sa.String(), nullable=False),
    sa.Column('bitrix_comment_id', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['briefing_session.session_id'], ),
    sa.PrimaryKeyConstraint('round_id'),
    sa.UniqueConstraint('session_id', 'round_number', name='uq_round_session_number')
    )
    op.create_table('go_authorization_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('high_risk_rule_applied', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_comment_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['briefing_session.session_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('briefing_question',
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('dor_dimension', sa.String(), nullable=True),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['briefing_round.round_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('briefing_answer',
    sa.Column('answer_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('answer_version', sa.Integer(), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_answer', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('source_comment_id', sa.String(), nullable=False),
    sa.Column('accepted_by_rule', sa.String(), nullable=False),
    sa.Column('author_user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['briefing_question.question_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_index('ix_answer_question_version', 'briefing_answer', ['question_id', 'answer_version'], unique=False)
    op.create_index('uq_answer_active_question', 'briefing_answer', ['question_id'], unique=True, postgresql_where=sa.text('superseded = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_answer_active_question', table_name='briefing_answer', postgresql_where=sa.text('superseded = false'))
    op.drop_index('ix_answer_question_version', table_name='briefing_answer')
    op.drop_table('briefing_answer')
    op.drop_table('briefing_question')
    op.drop_table('go_authorization_event')
    op.drop_table('briefing_round')
    op.drop_index('uq_session_active_task', table_name='briefing_session', postgresql_where=sa.text("state NOT IN ('APPROVED', 'BLOCKED_MANUAL', 'CANCELLED', 'ERROR', 'PLAN_GATE')"))
    op.drop_table('briefing_session')
    op.drop_table('task_state')
    op.drop_index('ix_audit_task_created', table_name='audit_event')
    op.drop_index('ix_audit_event_type', table_name='audit_event')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
